.PHONY: all
all: cmake
	make -C build

.PHONY: cmake
cmake:
	mkdir -p build
	cd build; cmake .. --graphviz=dep.dot --debug-output
	cd build; dot -Tpng -odep.png dep.dot

.POHONY: clean
clean:
	$(RM) -r build

